package de.lambda9.tailwind.core


class KIOException(val error: Cause<Any?>): Exception()